name: First Job
run-name: ${{ github.actor }} is running a first job
on:
    push: 
        branches: main
jobs:
  first_job:
    runs-on: macos-latest
    steps:
    - name: first action
      run: echo "First action"

    - name: Second action is to list files
      run: ls -lrthR
    
    - name: This action is to cat file
      run: uname -A

